import type { MantineColorsTuple } from '@mantine/core'

// generated by https://mantine.dev/colors-generator/?color=FF00FF
export const pink: MantineColorsTuple = [
  '#ffe8ff',
  '#ffcfff',
  '#ff9bff',
  '#ff64ff',
  '#fe38fe',
  '#fe1cfe',
  '#ff00ff', // main
  '#e400e4',
  '#cb00cb',
  '#b100b2',
]

export const cyan: MantineColorsTuple = [
  '#dfffff',
  '#caffff',
  '#99ffff',
  '#64ffff',
  '#3effff',
  '#26ffff',
  '#09ffff', // main
  '#00e3e3',
  '#00caca',
  '#00afaf',
]

export const SITE_COLOR = {
  'neutrals-white': '#ffffff',
  'neutrals-cool-gray-0': '#EEEEEE',
  'neutrals-cool-gray': '#333333',
  'neutrals-cool-gray-5': '#999999',
  'neutrals-beige': '#E8E3D8',
  'neutrals-cream': '#FAF8F3',
  'accents-cyan': '#09ffff',
  'accents-pink': '#ff00ff',
  'accents-yellow': '#FFFF00',
  'accents-red': '#ff0000',
  'accents-blue': '#0000FF',
  'ford-blue': '#0000FF',
}
