export { CardArticlePreview } from './card/index'
export { FooterContent } from './footer'
export { default as Footer } from './footer/Footer'
export { default as Form } from './form/RegisterForm'
export { default as Header } from './header/Header'
export * from './introSection'
export { ModalRegister } from './modal/index'
export * from './nextSection'
